/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Dенис' at '11.03.17 14:58' with Gradle 3.2.1
 *
 * @author Dенис, @date 11.03.17 14:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
